### PCTrackNet ###
model:
  pc:
    use_pc: true
    pc_encoder: pointnet # one of [pointnet]
    pc_out_size: 128
  track:
    use_track: true
    track_encoder: pointnet # one of [pointnet]
    track_out_size: 64
  decoder:
    name: transformer # one of [pool, lstm, transformer]
    dec_out_size: 8

### Dataclass ###
data:
  type: zod # one of [nuscenes, zod]
  version: mini
  split: train
  annotations:
    world_coord: true
    motion_compensate: true
  window_size: 25
  n_slides: 25
  #sliding_window: true
  #sw_augmentation: false # this can not be true used if sliding_window=True
  association_metric: giou #[giou, l2]
  association_thresholds:
    giou: 0.0
    l2: 2
  remove_bottom_center: false # if increases the z dimension by half the height for the detections
  remove_non_gt_tracks: false
  pc_offset: true
  transformations:
    center_offset: true
    yaw_offset: true
    normalize:
      normalize: false
      center:
        mean: [0.0, 0.0, 0.0]
        stdev: [1.0, 1.0,  1.0]
      size:
        mean: [0.0, 0.0, 0.0]
        stdev: [1.0, 1.0, 1.0]
      rotation:      
        mean: [0.0]
        stdev: [1.0]
      score:
        mean: [0.0]
        stdev: [1] 
    points:
      points_shift: false
      shift_max_size: 1
      points_scale: false
      scale_min: 0.9
      scale_max: 1.1


### Trainingdata Specific ###
train:
  learning_rate: 1.0E-4
  weight_decay: 1.0E-5
  train_size: 0.8
  batch_size: 150
  n_workers: 8
  n_epochs: 30
  eval_every: 1
  seed: 0

test:
  data:
    version: mini
    split: train

loss:
  type: "l1" # one of [l1, iou, giou]
  weight:
    center: 1
    size : 1
    rotation: 1
    score: 1