### WaymoPointNet ###
model:
  type: pointnet # one of [pointnet]
  pointnet:
    input_dim: 11 # center + size + rotation + class + temporal encoding # THESE SHOULD NOT BE IN CONFIG
    out_size: 11
    feat_size: 1024
    mlp1_sizes: [64,64,128,512]
    mlp2_sizes: [128,128]
    mlp3_sizes: [512,256]
  transformer:
    input_dim: 11
    out_size: 11
    mlp_sizes: [64,64,128,512]
    num_heads: 8

### Dataclass ###
data:
  type: zod # one of [nuscenes, zod]
  version: full
  split: val
  feature_dim: 11 #same as input_dim for the model
  foi_index: #20 # index in sequence where annotation exist TO BE REMOVED
  window_size: 15
  sliding_window: true
  gt_dim: 11 # same as out_dim for the model
  association_metric: giou #[giou, l2]
  association_thresholds:
    giou: -0.5
    l2: 10

  score_dist_temp: 1
  transformations:
    center_offset: true
    yaw_offset: true #not implemented yet
    normalize:
      normalize: true
      center: # this is offset-dependent normalization
        mean: [0.03621180372581629, -0.2099173730468761, 0.0026075183395728057]
        stdev: [5.865156088128115, 11.65336534100735, 0.4232649214239788]
      size:
        mean:  [3.664073049531213, 1.587799651724494, 1.7577496072774077]
        stdev: [4.607203312479755, 1.728919607809592, 1.8375323855211547]
      rotation:
        mean: [0.517103294721415, 0.0, 0.0, 0.5277412706723021]
        stdev: [0.6856551746488713, 1.0, 1.0, 0.7279287477380058]
      score:
        mean: [0.0]
        stdev: [1]

### Training Specific ###
train:
  data:
    version: full
    split: val 
  learning_rate: 1.0E-4
  weight_decay: 1.0E-5
  train_size: 0.8
  batch_size: 100
  n_workers: 1
  n_epochs: 5
  seed: 0

test:
  data:
    version: full
    split: val

loss:
  type: "l1" # one of [l1, iou, giou]
  weight:
    center: 2
    size : 1
    rotation: 1
    score: 1