### PCTrackNet ###
model:
  early_fuse: # fuse points and tracks before encoding
    early_fuse: true
    fuse_encoder: pointnet # one of [pointnet]
    encoder_out_size: 128
  pc:
    use_pc: true
    pc_encoder: pointnet # one of [pointnet]
    pc_out_size: 128
  track:
    use_track: true
    track_encoder: pointnet # one of [pointnet]
    track_out_size: 64
  temporal_encoder: transformer # one of [pool, lstm, transformer]
  dec_out_size: 8

### Dataclass ###
data:
  type: zod # one of [zod]
  version: full
  split: train
  annotations:
    world_coord: true
    motion_compensate: true
  window_size: 15
  times: 1
  random_slides: true    
  association_metric: iou # one of [iou]
  association_thresholds:
    iou: 0.2
    giou: -0.5
    l2: 2
  remove_bottom_center: false # if increases the z dimension by half the height for the detections
  remove_non_gt_tracks: false
  pc_offset: true
  transformations:
    center_offset: true
    yaw_offset: true
    normalize:
      normalize: false
      center:
        mean: [0.0, 0.0, 0.0]
        stdev: [1.0, 1.0,  1.0]
      size:
        mean: [0.0, 0.0, 0.0]
        stdev: [1.0, 1.0, 1.0]
      rotation:      
        mean: [0.0]
        stdev: [1.0]
      score:
        mean: [0.0]
        stdev: [1] 
    points:
      points_shift: false
      shift_max_size: 0.1
      points_scale: false


### Trainingdata Specific ###
train:
  learning_rate: 1.0E-4
  weight_decay: 0
  train_size: 0.9
  batch_size: 150
  n_workers: 8
  n_epochs: 200
  eval_every: 1
  seed: 0

test:
  data:
    version: mini
    split: train

loss:
  type: "l1" # one of [l1]
  weight:
    center: 1.0
    size : 1.0
    rotation: 1.0
    score: 1.0