### PCTrackNet ###
model:
  pc:
    use_pc: true
    pc_encoder: pointnet # one of [pointnet]
    pc_out_size: 128
  track:
    use_track: true
    track_encoder: pointnet # one of [pointnet]
    track_out_size: 64
  decoder:
    name: transformer # one of [pool, lstm, transformer]
    dec_out_size: 8

### Dataclass ###
data:
  type: zod # one of [nuscenes, zod]
  version: mini
  split: train
  annotations:
    world_coord: true
    motion_compensate: true
  window_size: 25
  sliding_window: false
  sw_augmentation: false # this can not be true used if sliding_window=True
  association_metric: l2 #[giou, l2]
  association_thresholds:
    giou: 0.0
    l2: 2
  remove_bottom_center: false # if increases the z dimension by half the height for the detections
  remove_non_gt_tracks: false
  score_dist_temp: 1
  pc_offset: true
  transformations:
    center_offset: true
    yaw_offset: true
    normalize:
      normalize: true
      center:
        mean: [6.08003332e+01, -5.48336047e-01, 1.43935423e-01] #offset
        stdev: [91.38101561, 25.21201567, 2.18470847] #offset
        #mean: [1.73462339e+02,9.52634063e-02,7.67952893e-01]
        #stdev: [136.05763403,41.14419256,3.29430988]
      size:
        mean: [4.91675939e+00, 2.00343822e+00, 1.82337010e+00] #offset
        stdev: [2.51673582, 0.30871848, 0.65036061] #offset
        #mean: [4.91675939e+00, 2.00343822e+00, 1.82337010e+00]
        #stdev: [2.51673582, 0.30871848,0.65036061]
      rotation:      
        mean: [0] #[5.11720420e-02]
        stdev: [1] #[1.25795325]
      score:
        mean: [0.0]
        stdev: [1] 
    points:
      points_shift: true
      shift_max_size: 1
      points_scale: true
      scale_min: 0.9
      scale_max: 1.1


### Trainingdata Specific ###
train:
  learning_rate: 1.0E-4
  weight_decay: 1.0E-5
  train_size: 0.8
  batch_size: 8
  n_workers: 8
  n_epochs: 200
  eval_every: 1
  seed: 0

test:
  data:
    version: mini
    split: train

loss:
  type: "l1" # one of [l1, iou, giou]
  weight:
    center: 1
    size : 1
    rotation: 1
    score: 1