### PCTrackNet ###
model:
  pc:
    use_pc: true
    pc_encoder: pointnet # one of [pointnet]
    pc_out_size: 256
  track:
    use_track: true
    track_encoder: pointnet # one of [pointnet]
    track_out_size: 64
  decoder:
    name: lstm # one of [pool, lstm, transformer]
    dec_out_size: 16

### Dataclass ###
data:
  type: zod # one of [nuscenes, zod]
  version: full
  split: train
  foi_index: #20 # index in sequence where annotation exist TO BE REMOVED
  window_size: 25
  sliding_window: true
  association_metric: giou #[giou, l2]
  association_thresholds:
    giou: 0.0
    l2: 2
  remove_bottom_center: true # if increases the z dimension by half the height for the detections

  score_dist_temp: 1
  pc_offset: true
  transformations:
    center_offset: true
    yaw_offset: false #not implemented yet
    normalize:
      normalize: true
      center:
        mean: [-1.0408938187128578, 15.676385645189473, -0.5681853294492015]
        stdev: [8.827627848858757, 19.47008377654335, 0.6877734215244837]
      size:
        mean: [2.5877273679628194, 1.0347822035160879, 0.9536876676924065]
        stdev: [3.1708958713662074, 1.0381670406742867, 1.0549146278354404]
      rotation:      
        mean: [-0.3136310277276827, -0.013401212689278484]
        stdev: [0.5951111005230132, 0.24225834247964198]
      score:
        mean: [0.0]
        stdev: [1]

### Training Specific ###
train:
  learning_rate: 1.0E-5
  weight_decay: 1.0E-5
  train_size: 0.8
  batch_size: 50
  n_workers: 8
  n_epochs: 20
  seed: 0

test:
  data:
    version: full
    split: val

loss:
  type: "l1" # one of [l1, iou, giou]
  weight:
    center: 1
    size : 1
    rotation: 1
    score: 1