### PCTrackNet ###
model:
  pc:
    use_pc: true
    pc_encoder: pointnet # one of [pointnet]
    pc_out_size: 128
  track:
    use_track: true
    track_encoder: pointnet # one of [pointnet]
    track_out_size: 64
  decoder:
    name: transformer # one of [pool, lstm, transformer]
    dec_out_size: 8

### Dataclass ###
data:
  type: zod # one of [nuscenes, zod]
  version: full
  split: train
  window_size: 25
  sliding_window: false
  sw_augmentation: false # this can not be true used if sliding_window=True
  association_metric: l2 #[giou, l2]
  association_thresholds:
    giou: 0.0
    l2: 2
  remove_bottom_center: true # if increases the z dimension by half the height for the detections
  remove_non_gt_tracks: false
  score_dist_temp: 1
  pc_offset: false
  transformations:
    center_offset: true
    yaw_offset: true
    normalize:
      normalize: true
      center:
        mean: [-1.0408938187128578, 15.676385645189473, -0.5681853294492015]
        stdev: [8.827627848858757, 19.47008377654335, 0.6877734215244837]
      size:
        mean: [2.5877273679628194, 1.0347822035160879, 0.9536876676924065]
        stdev: [3.1708958713662074, 1.0381670406742867, 1.0549146278354404]
      rotation:      
        mean: [0.0]#[-0.3136310277276827, -0.013401212689278484]
        stdev: [1.0]#[0.5951111005230132, 0.24225834247964198]
      score:
        mean: [0.0]
        stdev: [1] 
    points:
      points_shift: true
      shift_max_size: 1
      points_scale: true
      scale_min: 0.9
      scale_max: 1.1


### Training Specific ###
train:
  learning_rate: 1.0E-4
  weight_decay: 1.0E-5
  train_size: 0.8
  batch_size: 4
  n_workers: 8
  n_epochs: 20
  eval_every: 1
  seed: 0

test:
  data:
    version: full
    split: val

loss:
  type: "l1" # one of [l1, iou, giou]
  weight:
    center: 1
    size : 1
    rotation: 1
    score: 1