running:
  covariance: default
  score_threshold: 0.3 #0.01
  max_age_since_update: 4
  min_hits_to_birth: 2
  match_type: bipartite
  asso: giou
  has_velo: false #not used?
  #nms_thres: 0.1 #not used?
  motion_model: kf
  asso_thres:
    giou: 1.3 
    iou: 0.9

redundancy:
  mode: mm
  det_score_threshold: 
    iou: 0.1 #0.01
    giou: 0.01 #0.01
  det_dist_threshold: 
    iou: 0.1
    giou: -0.5

data_loader:
  pc: false 
  nms: true
  nms_thres: 0.25